services:
  - type: static_site
    name: freelab-hub-piloto
    env: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
